name: Simple Deploy with Password

on:
  push:
    branches: [ "main" ] # غيريها لو تبّي فرع آخر

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH with Password
        uses: appleboy/ssh-action@master
        with:
          host: thegoatacademy.net.ly
          username: thegoata
          password: ';NXv%WzVSp:g'
          port: 6934
          script: |
            cd public_html
            git pull origin main
            php artisan migrate --force
